# Generated by Django 5.0.6 on 2024-07-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='prod',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='category1',
            field=models.CharField(choices=[('Electronics', 'electronics'), ('Fashion', 'fashion'), ('Books', 'books'), ('Building Material', 'building material'), ('Stationary', 'stationary'), ('Fashion', 'fashine'), ('Furniture', 'furniture')], default='AGENT', max_length=100),
        ),
    ]
