# Generated by Django 5.0.6 on 2024-07-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_myuser_prod_alter_myuser_category1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='logo',
            field=models.ImageField(upload_to='store_logo'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='qrImg',
            field=models.ImageField(upload_to='user_qr'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='storeQrImg',
            field=models.ImageField(upload_to='store_qr'),
        ),
    ]
