# Generated by Django 5.0.6 on 2024-07-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_myuser_logo_alter_myuser_qrimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='storeQrImg',
            field=models.ImageField(upload_to='Store_qr'),
        ),
    ]
